language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
sudo: false
install: true
services:
  - xvfb
addons:
  sonarcloud:
    organization: dp-dev-github
    token:
      secure: $SONAR_TOKEN
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - mvn clean install
  - sonar-scanner
cache:
  directories:
  - $HOME/.sonar/cache
  - $HOME/.m2

