language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
sudo: false
install: true
services:
  - xvfb
addons:
  sonarcloud:
    organization: dp-dev-github
    token:
      secure: $SONAR_TOKEN
before_script:
  - "export DISPLAY=:99.0"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
